server:
  port: 8001

spring:
  application:
    name: dubbo-user-service-provider

dubbo:
  # 注册中心地址
  registry:
    address: nacos://192.168.2.125:8848/
#    host: 192.168.2.100
  protocol:
    name: dubbo
    port: 20880
    host: 192.168.2.100
